INSERT INTO CUSTOMER (name, address, priority) VALUES ('Phillip','Taiwan','Normal');
INSERT INTO CUSTOMER (name, address, priority) VALUES ('Vency','Taiwan','Premium');
INSERT INTO COUNTER (COUNTER_TYPE, STATUS,COUNTER_STATUS) VALUES ('P','active','OPEN');
INSERT INTO COUNTER (COUNTER_TYPE, STATUS,COUNTER_STATUS) VALUES ('N','active','OPEN');
INSERT INTO COUNTER (COUNTER_TYPE, STATUS,COUNTER_STATUS) VALUES ('P','active','OPEN');
INSERT INTO COUNTER (COUNTER_TYPE, STATUS,COUNTER_STATUS) VALUES ('P','active','OPEN');